### PR TITLE
Add NTSC-J, NTSC 4.43, B/W 625 and B/W 525 TV modes (untested)

### PR DESCRIPTION
**Pull request by Zcooger**

### CODE REVIEW

**Comment by Zcooger** [comment]
NTSC:
image
Japanese NTSC:
image
NTSC 4.43:
image
B/W 525:
image
625 B/W with Videocrypt:
image

**Comment by ejelly** [comment]
The color ones look pretty pad (in the other thread with PAL as well), with a lot of cross-luminance patterns (I'm not talking about the colorful dots in the foreground of the first two pictures, but about the actual test pattern appearance). What capture device do you use? Can you switch it to use different filters?

**Comment by Zcooger** [comment]
Currently I'm working with terrible cx2388 card. Hopefully I will soon test it with saa7134 which has much better filters. The cx one does not have any besides simple comb filter and delay line (they are on).

**Comment by Zcooger** [comment]
Here's PAL for comparison (card calibration is done):
image
Pay And Look.

**Comment by ejelly** [comment]
Ah, in any case, it's well enough for verifying that the modes work properly!

**Comment by fsphil** [comment]
A few quick comments:

* VID_RASTER_625_BW and VID_RASTER_525_BW are unnecessary, the structure of the frame is unaffected by the presence or absence of colour. It's enough to simply not specify the colour mode - the default is none.
* Changing "PAL only" to "625 only" isn't really correct for Videocrypt 1 + 2 as they can't work with SECAM 625 line.
* Same with the 625 line-only teletext. The current version of SECAM 625 line won't work with teletext.
* I'm not a fan of the tabular model list in the help text.

Everything else looks good though!

**Pull request closed without merging**
